### ISSUE TITLE
Black Borders when not in fullscreen on windows

### ISSUE THREAD

**Issue by winpower21** [flxzt/rnote#842]
**Describe the bug**  
Thick black borders around the window when not in fullscreen on windows

**To Reproduce**  
1. Install Rnote on windows 11
2. Run Rnote

**Expected behavior**  
No black borders around the window.

**Screenshots**  
![image](https://github.com/flxzt/rnote/assets/95289325/6c4a674a-9506-421f-ae0c-d8a1cf53f166)

Desktop:
 - OS: Windows 11 22H2 22621.2428
 - App Version: Rnote v0.9.0
 - Installation Source: .exe installer as well as winget

**Comment by flxzt** [comment]
Is this still consistently happening for you? It looks like the compositing failed. I saw this personally on linux as well, but not specifical to Rnote and usually only when a crash in the desktop environment/the compositor happened.

**Comment by Doublonmousse** [comment]
Maybe related ? https://gitlab.gnome.org/GNOME/gtk/-/issues/6401 
It _might_ be fixed on gtk 4.14 regardless of the renderer for nvidia graphics cards (gl or ngl, the gl one was reported to have black borders)

**Comment by Doublonmousse** [comment]
From #1197
> <img alt="Snipaste_2024-09-01_17-53-09" width="893" src="https://private-user-images.githubusercontent.com/18170946/363482205-d10a0216-cb57-459b-8de7-43431b1a14cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxODY2MzksIm5iZiI6MTcyNTE4NjMzOSwicGF0aCI6Ii8xODE3MDk0Ni8zNjM0ODIyMDUtZDEwYTAyMTYtY2I1Ny00NTliLThkZTctNDM0MzFiMWExNGNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDEwMjUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlM2E4NjVkN2I0ODIzMzU4NmE3MDhlZDQ2YmRkOTA2OTE5YjllNGY1Yzg5NDUzMTU2NzVkYmM3YzcwNjRmOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mgkY54gnxxIoSynSaKmafqVWvI3eXEn7tIi6aexRXaM">
> 版本 Windows 11 专业版 版本号 23H2 安装日期 ‎2024/‎8/‎26 操作系统版本 22631.4112 体验 Windows Feature Experience Pack 1000.22700.1034.0
> 
> [显示] DirectX 版本： 12.0 GPU 处理器： NVIDIA GeForce RTX 3050 4GB Laptop GPU 驱动程序版本： 560.94 驱动器类型： DCH Direct3D 功能级别： 12_1 CUDA 核心： 2560 Max-Q 技术 是 动态增强 是 WhisperMode 否 高级 Optimus 否 显卡最大功率 50 W 核心时钟： 1365 MHz 内存数据速率： 14.00 Gbps 内存接口： 64-位 内存带宽： 112.02 GB/秒 全部可用的图形内存： 20308MB 专用视频内存： 4096 MB GDDR6 系统视频内存： 0MB 共享系统内存： 16212MB 视频 BIOS 版本： 94.07.87.00.4D IRQ： Not used 总线： PCI Express x4 设备 ID： 10DE 25AB 50D417AA 部件编号： 4728 0010
> 
> [组件]
> 
> nvui.dll 8.17.15.6094 NVIDIA User Experience Driver Component nvxdplcy.dll 8.17.15.6094 NVIDIA User Experience Driver Component nvxdbat.dll 8.17.15.6094 NVIDIA User Experience Driver Component nvxdapix.dll 8.17.15.6094 NVIDIA User Experience Driver Component NVCPL.DLL 8.17.15.6094 NVIDIA User Experience Driver Component nvCplUIR.dll 8.1.940.0 NVIDIA Control Panel nvCplUI.exe 8.1.940.0 NVIDIA Control Panel nvLicensingS.dll 6.14.15.6094 NVIDIA Licensing Server nvViTvSR.dll 32.0.15.6094 NVIDIA Video Server nvViTvS.dll 32.0.15.6094 NVIDIA Video Server nvDispSR.dll 32.0.15.6094 NVIDIA Display Server nvDispS.dll 32.0.15.6094 NVIDIA Display Server nvDevToolSR.dll 32.0.15.6094 NVIDIA Licensing Server nvDevToolS.dll 32.0.15.6094 NVIDIA 3D Settings Server nvWSSR.dll 32.0.15.6094 NVIDIA Workstation Server nvWSS.dll 32.0.15.6094 NVIDIA Workstation Server PhysX 09.23.1019 NVIDIA PhysX NVCUDA64.DLL 32.0.15.6094 NVIDIA CUDA 12.6.65 driver nvGameSR.dll 32.0.15.6094 NVIDIA 3D Settings Server nvGameS.dll 32.0.15.6094 NVIDIA 3D Settings Server

**Comment by Doublonmousse** [comment]
Tracking upstream issue : https://gitlab.gnome.org/GNOME/gtk/-/issues/7001
and another related message : https://gitlab.gnome.org/GNOME/gtk/-/issues/6975#note_2215037

Basically the shadow is drawn by gtk and it doesn't always work (hence the black bar). We'll have to wait on gtk to use windows's built in shadows, that should fix this

**Comment by Doublonmousse** [comment]
With the 0.12, if the shadow drawing fails like before, it _should_ be significantly smaller.

There's also a gtk version bump (with a change of renderer) so this may behave differently now

**Comment by MisterAnonym1** [comment]
I am on Windows and experiencing the same issue (although my borders are slightly smaller). Would it be possible, as long as the issue isn't fixed upstream, to push a small fix, which just disables the gtk shadow in the Windows version?
