### ISSUE TITLE
"Opened file was modified on disk" pop up when saved

### ISSUE THREAD

**Issue by MisterE123** [flxzt/rnote#990]
**Describe the bug**  
Whenever the file is saved, via autosave or manual save, the following pup up appears after a second or so:
![image](https://github.com/flxzt/rnote/assets/61124264/9444874b-61be-4038-a4f7-80b14f129477)

**To Reproduce**  
1. be on windows
2. save the file

**Expected behavior**  
Just save the file, don't give that annoying pop up

**Desktop (please complete the following information):**  
 - OS: Windows 11
 - App Version: Rnote v0.9.4
 - Installation Source: Windows installer

**Comment by ImTheCurse** [comment]
It only seems to happen to me when I save the .rnote files on oneDrive / google drive, but not on local save.

**Comment by MisterE123** [comment]
I am saving the files on my onedrive filesystem

**Comment by digitalsignalperson** [comment]
I'm on linux with ZFS and I'm seeing this "Opened file was modified on disk" on autosave. One time I clicked it and it reverted my file to be empty.

**Comment by flxzt** [comment]
Can you run the app with trace logging enabled (Either `flatpak --env=RUST_LOG=rnote=debug run com.github.flxzt.rnote` or `RUST_LOG=rnote=debug rnote` ) and post the output, excluding the pointer events?

**Comment by digitalsignalperson** [comment]
I realize I had two instances open. One was on a 3rd virtual desktop which I didn't notice. It had the file open when it was just empty. So it was overwriting the file with an empty copy. When I looked back in my ZFS snapshot history, the file sizes were alternating between 256KB and 743 bytes (empty). Today I opened the file and it was empty, and I realized there was the extra instance open. Unfortunately I didn't have the right snapshot for the last 6 hours or so so lost some notes.

Should I open a separate feature request for something like: "prevent same file being auto-saved in multiple instances"?

**Comment by olbotta** [comment]
to me this happens when i save very quickly twice a file

**Comment by MisterE123** [comment]
This may have been fixed on the latest version (0.11.0)

You could add possible close @flxzt

**Comment by Doublonmousse** [comment]
@digitalsignalperson I'm opening another issue for this #1424 

@olbotta @ImTheCurse Does it still happen on 0.11 or 0.12? If so, is it with cloud storage? 
If this is only with cloud storage, I'll close this in favor of #461 for the cloud storage part

**Comment by ImTheCurse** [comment]
> @digitalsignalperson I'm opening another issue for this #1424 
> 
> @olbotta @ImTheCurse Does it still happen on 0.11 or 0.12? If so, is it with cloud storage? 
> If this is only with cloud storage, I'll close this in favor of #461 for the cloud storage part

Yeah, only for cloud storage,
Saving on disk seems to work fine.

**Comment by olbotta** [comment]
> [@olbotta](https://github.com/olbotta) [@ImTheCurse](https://github.com/ImTheCurse) Does it still happen on 0.11 or 0.12? If so, is it with cloud storage?
version 0.12.0 still happens. no cloud storage. you just have to press ctrl+s fast enough and you will get that error
